// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'hamburger': string;
  'items': string;
  'logo': string;
  'main': string;
  'navigation': string;
  'overlay': string;
  'wordmark': string;
}
export const cssExports: CssExports;
export default cssExports;
