// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'cta': string;
  'label': string;
  'secondaryLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
