// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authentication': string;
  'avatar': string;
  'background': string;
  'controls': string;
  'hamburger': string;
  'item': string;
  'label': string;
  'list': string;
  'logo': string;
  'navigation': string;
  'overlay': string;
  'signup': string;
  'signupContent': string;
  'sublabel': string;
  'wordmark': string;
}
export const cssExports: CssExports;
export default cssExports;
