export { SocialDiscord as IconSocialDiscord } from "./SocialDiscord"
export { SocialDribbble as IconSocialDribbble } from "./SocialDribbble"
export { SocialFacebook as IconSocialFacebook } from "./SocialFacebook"
export { SocialGoogle as IconSocialGoogle } from "./SocialGoogle"
export { SocialLinkedIn as IconSocialLinkedIn } from "./SocialLinkedIn"
export { SocialSlack as IconSocialSlack } from "./SocialSlack"
export { SocialSpectrum as IconSocialSpectrum } from "./SocialSpectrum"
export { SocialTwitter as IconSocialTwitter } from "./SocialTwitter"
