// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'containerL': string;
  'containerXl': string;
}
export const cssExports: CssExports;
export default cssExports;
