// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addendum': string;
  'badge': string;
  'footer': string;
  'heading': string;
  'item': string;
  'items': string;
  'list': string;
  'separator': string;
  'social': string;
}
export const cssExports: CssExports;
export default cssExports;
