// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menuSubnavigation': string;
  'searchSubnavigation': string;
}
export const cssExports: CssExports;
export default cssExports;
