import { palette } from "./palette"
import { rgba } from "../utils"
import { Color } from "."

export const colorDark: Color = {
  border: palette.dark80,
  borderHighlight: "rgba(255, 255, 255, 0.1)",
  buttonBackground: palette.dark80,
  buttonColor: palette.white,
  buttonDangerBackground: palette.red,
  buttonDangerColor: palette.white,
  buttonDangerFocusOutline: "rgba(255, 255, 255, 0.06)",
  buttonDangerHoverBackground: palette.redLight,
  buttonFocusOutline: "rgba(255, 255, 255, 0.06)",
  buttonHoverBackground: palette.dark70,
  buttonIconColor: palette.light60,
  buttonIconHoverColor: palette.light56,
  buttonPrimaryBackground: palette.blue,
  buttonPrimaryColor: palette.white,
  buttonPrimaryFocusOutline: "rgba(255, 255, 255, 0.06)",
  buttonPrimaryHoverBackground: palette.blueLight,
  buttonSecondaryBackground: palette.deepBlue,
  buttonSecondaryColor: palette.white,
  buttonSecondaryFocusOutline: "rgba(255, 255, 255, 0.06)",
  buttonSecondaryHoverBackground: palette.deepBlueLight,
  buttonSuccessBackground: palette.green,
  buttonSuccessColor: palette.white,
  buttonSuccessFocusOutline: "rgba(0, 0, 0, 0.04)",
  buttonSuccessHoverBackground: palette.greenLight,
  danger: palette.red,
  dangerDark: palette.redDark,
  footerBackground: palette.dark100,
  footerCookiesLink: palette.light60,
  footerCopyrightLink: palette.light52,
  footerIcon: palette.dark40,
  footerIconHover: palette.blue,
  footerLink: palette.light80,
  inputBackground: palette.dark80,
  inputBackgroundTransparent: rgba(palette.dark80, 0),
  inputColor: palette.white,
  inputDangerColor: palette.red,
  inputDangerFocusBorder: palette.red,
  inputDisabledColor: palette.dark70,
  inputFocusBorder: palette.blue,
  inputHoverBackground: palette.dark30,
  inputPlaceholderColor: palette.dark20,
  listActiveBackground: palette.dark90,
  listBorder: palette.dark80,
  listColor: palette.dark20,
  navigationBackground: palette.dark100,
  navigationBorder: "rgba(255, 255, 255, 0.06)",
  navigationColor: palette.white,
  overlayColor: "rgba(0, 0, 0, 0.75)",
  pageBackground: palette.dark94,
  pageColor: palette.white,
  primary: palette.blue,
  primaryColor: palette.white,
  primaryDark: palette.blueDark,
  primaryLight: palette.blueLight,
  searchBackground: palette.light52,
  secondary: palette.dark80,
  secondaryColor: palette.dark20,
  secondaryDark: palette.dark90,
  secondaryLight: palette.dark90,
  selection: palette.white,
  selectionBackground: "rgba(0, 170, 255, 0.99)",
  selectionBackgroundFaint: "rgba(0, 170, 255, 0.4)",
  sheetBackground: palette.dark82,
  sheetColor: palette.white,
  sidebarLink: palette.dark20,
  success: palette.green,
  successDark: palette.greenDark,
  tertiary: palette.purple,
  textBody: palette.light92,
  textDimmed: palette.dark50,
  textHeadline: palette.white,
  textLight: palette.dark20,
  toolbarIcon: palette.dark20,
  tooltipBackground: palette.dark80,
  wireframe: rgba(palette.redLight, 0.08),
  translucent: "rgba(0, 0, 0, .5)",
  vibrant: "rgba(0, 0, 0, .8)",
}
