import { paletteTokens } from "./palette"
import { rgba } from "../utils"
import { Color } from "."

export const colorTokensDark: Color = {
  border: paletteTokens.dark80,
  borderHighlight: "rgba(255, 255, 255, 0.1)",
  buttonBackground: paletteTokens.dark80,
  buttonColor: paletteTokens.white,
  buttonDangerBackground: paletteTokens.red,
  buttonDangerColor: paletteTokens.white,
  buttonDangerFocusOutline: "rgba(255, 255, 255, 0.06)",
  buttonDangerHoverBackground: paletteTokens.redLight,
  buttonFocusOutline: "rgba(255, 255, 255, 0.06)",
  buttonHoverBackground: paletteTokens.dark70,
  buttonIconColor: paletteTokens.light60,
  buttonIconHoverColor: paletteTokens.light56,
  buttonPrimaryBackground: paletteTokens.blue,
  buttonPrimaryColor: paletteTokens.white,
  buttonPrimaryFocusOutline: "rgba(255, 255, 255, 0.06)",
  buttonPrimaryHoverBackground: paletteTokens.blueLight,
  buttonSecondaryBackground: paletteTokens.deepBlue,
  buttonSecondaryColor: paletteTokens.white,
  buttonSecondaryFocusOutline: "rgba(255, 255, 255, 0.06)",
  buttonSecondaryHoverBackground: paletteTokens.deepBlueLight,
  buttonSuccessBackground: paletteTokens.green,
  buttonSuccessColor: paletteTokens.white,
  buttonSuccessFocusOutline: "rgba(0, 0, 0, 0.04)",
  buttonSuccessHoverBackground: paletteTokens.greenLight,
  danger: paletteTokens.red,
  dangerDark: paletteTokens.redDark,
  footerHeading: paletteTokens.white,
  footerLink: paletteTokens.light80,
  footerSecondary: paletteTokens.dark40,
  inputBackground: paletteTokens.dark80,
  inputBackgroundTransparent: rgba(paletteTokens.dark80, 0),
  inputColor: paletteTokens.white,
  inputDangerColor: paletteTokens.red,
  inputDangerFocusBorder: paletteTokens.red,
  inputDisabledColor: paletteTokens.dark70,
  inputFocusBorder: paletteTokens.blue,
  inputHoverBackground: paletteTokens.dark30,
  inputPlaceholderColor: paletteTokens.dark20,
  listActiveBackground: paletteTokens.dark90,
  listBorder: paletteTokens.dark80,
  listColor: paletteTokens.dark20,
  navigationBackground: paletteTokens.dark100,
  navigationBorder: "rgba(255, 255, 255, 0.06)",
  navigationColor: paletteTokens.white,
  navigationHamburger: paletteTokens.white,
  overlayColor: "rgba(0, 0, 0, 0.5)",
  pageBackground: paletteTokens.dark100,
  pageColor: paletteTokens.white,
  primary: paletteTokens.blue,
  primaryColor: paletteTokens.white,
  primaryDark: paletteTokens.blueDark,
  primaryLight: paletteTokens.blueLight,
  searchBackground: paletteTokens.light52,
  secondary: paletteTokens.dark80,
  secondaryColor: paletteTokens.dark20,
  secondaryDark: paletteTokens.dark90,
  secondaryLight: paletteTokens.dark90,
  selection: paletteTokens.white,
  selectionBackground: "rgba(0, 170, 255, 0.99)",
  selectionBackgroundFaint: "rgba(0, 170, 255, 0.4)",
  sheetBackground: paletteTokens.dark82,
  sheetColor: paletteTokens.white,
  sidebarLink: paletteTokens.dark20,
  success: paletteTokens.green,
  successDark: paletteTokens.greenDark,
  tertiary: paletteTokens.purple,
  textBody: paletteTokens.light92,
  textDimmed: paletteTokens.dark50,
  textHeadline: paletteTokens.white,
  textLight: paletteTokens.dark20,
  toolbarIcon: paletteTokens.dark20,
  tooltipBackground: paletteTokens.dark80,
  wireframe: rgba(paletteTokens.redLight, 0.08),
  translucent: "rgba(0, 0, 0, .5)",
  vibrant: "rgba(0, 0, 0, .8)",
}
