import { paletteTokens } from "./palette"
import { rgba } from "../utils"
import { Color } from "."

export const colorTokens: Color = {
  border: paletteTokens.light54,
  borderHighlight: "rgba(0, 0, 0, 0.05)",
  buttonBackground: paletteTokens.light58,
  buttonColor: paletteTokens.black,
  buttonDangerBackground: paletteTokens.red,
  buttonDangerColor: paletteTokens.white,
  buttonDangerFocusOutline: "rgba(255, 255, 255, 0.06)",
  buttonDangerHoverBackground: paletteTokens.redDark,
  buttonFocusOutline: "rgba(0, 0, 0, 0.04)",
  buttonHoverBackground: paletteTokens.light62,
  buttonIconColor: paletteTokens.dark20,
  buttonIconHoverColor: paletteTokens.dark30,
  buttonPrimaryBackground: paletteTokens.blue,
  buttonPrimaryColor: paletteTokens.white,
  buttonPrimaryFocusOutline: "rgba(0, 0, 0, 0.04)",
  buttonPrimaryHoverBackground: paletteTokens.blueDark,
  buttonSecondaryBackground: paletteTokens.deepBlue,
  buttonSecondaryColor: paletteTokens.white,
  buttonSecondaryFocusOutline: "rgba(0, 0, 0, 0.04)",
  buttonSecondaryHoverBackground: paletteTokens.deepBlueDark,
  buttonSuccessBackground: paletteTokens.green,
  buttonSuccessColor: paletteTokens.white,
  buttonSuccessFocusOutline: "rgba(0, 0, 0, 0.04)",
  buttonSuccessHoverBackground: paletteTokens.greenDark,
  danger: paletteTokens.red,
  dangerDark: paletteTokens.redDark,
  footerHeading: paletteTokens.dark100,
  footerLink: paletteTokens.dark80,
  footerSecondary: paletteTokens.dark30,
  inputBackground: paletteTokens.light58,
  inputBackgroundTransparent: rgba(paletteTokens.light58, 0),
  inputColor: paletteTokens.dark100,
  inputDangerColor: paletteTokens.red,
  inputDangerFocusBorder: paletteTokens.red,
  inputDisabledColor: paletteTokens.light80,
  inputFocusBorder: paletteTokens.blue,
  inputHoverBackground: paletteTokens.light56,
  inputPlaceholderColor: paletteTokens.light92,
  listActiveBackground: paletteTokens.light56,
  listBorder: paletteTokens.light52,
  listColor: paletteTokens.dark80,
  navigationBackground: paletteTokens.white,
  navigationBorder: "rgba(0, 0, 0, 0.05)",
  navigationColor: paletteTokens.dark100,
  navigationHamburger: paletteTokens.dark60,
  overlayColor: "rgba(0, 0, 0, 0.5)",
  pageBackground: paletteTokens.white,
  pageColor: paletteTokens.black,
  primary: paletteTokens.blue,
  primaryColor: paletteTokens.white,
  primaryDark: paletteTokens.blueDark,
  primaryLight: paletteTokens.blueLight,
  searchBackground: paletteTokens.dark100,
  secondary: paletteTokens.light58,
  secondaryColor: paletteTokens.dark70,
  secondaryDark: paletteTokens.light54,
  secondaryLight: paletteTokens.dark60,
  selection: paletteTokens.white,
  selectionBackground: "rgba(0, 170, 255, 0.99)",
  selectionBackgroundFaint: "rgba(0, 170, 255, 0.4)",
  sheetBackground: paletteTokens.white,
  sheetColor: paletteTokens.dark100,
  sidebarLink: paletteTokens.dark100,
  success: paletteTokens.green,
  successDark: paletteTokens.greenDark,
  tertiary: paletteTokens.purple,
  textBody: paletteTokens.dark100,
  textDimmed: paletteTokens.dark20,
  textHeadline: paletteTokens.black,
  textLight: paletteTokens.dark60,
  toolbarIcon: paletteTokens.light100,
  tooltipBackground: paletteTokens.light100,
  wireframe: rgba(paletteTokens.red, 0.08),
  translucent: "rgba(255, 255, 255, .6)",
  vibrant: "rgba(255, 255, 255, .9)",
}
