// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'sizeLarge': string;
  'sizeLarger': string;
  'sizeSmall': string;
}
export const cssExports: CssExports;
export default cssExports;
